const crypto = require('crypto');

const EVENT_SLUG = 'feria-usado-con-ruedas-2027';
const EVENT_NAME = 'La Feria del Usado con Ruedas 2027';
const EVENT_TIME_ZONE = 'America/Argentina/Buenos_Aires';

const PRODUCTS = {
  entrada_general: { code: 'entrada_general', name: 'Entrada general anticipada', amount: 10000, prefix: 'GEN', requiresVehicle: false, includesBox: false, description: 'Ingreso general anticipado. Válido para los 4 días del evento.' },
  caja_ruta_vehiculo: { code: 'caja_ruta_vehiculo', name: 'Caja Ruta Stylo Camión + ingreso vehicular', amount: 20000, prefix: 'RUTA', requiresVehicle: true, includesBox: true, description: 'Caja rutera online con ingreso vehicular incluido. En puerta, mismo valor sin caja.' },
  ingreso_camion: { code: 'ingreso_camion', name: 'Ingreso con camión', amount: 35000, prefix: 'CAM', requiresVehicle: true, includesBox: false, description: 'Ingreso del camión al predio. Válido para los 4 días del evento.' },
  ingreso_auto_pickup: { code: 'ingreso_auto_pickup', name: 'Ingreso auto / pick-up', amount: 20000, prefix: 'AUT', requiresVehicle: true, includesBox: false, description: 'Ingreso de auto o pick-up al predio. Válido para los 4 días del evento.' },
  ingreso_moto: { code: 'ingreso_moto', name: 'Ingreso moto', amount: 15000, prefix: 'MOT', requiresVehicle: true, includesBox: false, description: 'Ingreso de moto al predio. Válido para los 4 días del evento.' },
  estacionamiento_visitante: { code: 'estacionamiento_visitante', name: 'Estacionamiento visitante', amount: 10000, prefix: 'EST', requiresVehicle: true, includesBox: false, description: 'Estacionamiento visitante. Valor editable desde configuración del sistema.' }
};

function getBaseUrl(req) {
  const configured = process.env.PUBLIC_BASE_URL || process.env.SITE_URL || process.env.VERCEL_PROJECT_PRODUCTION_URL;
  if (configured) return configured.startsWith('http') ? configured.replace(/\/$/, '') : `https://${configured.replace(/\/$/, '')}`;
  const proto = req.headers['x-forwarded-proto'] || 'https';
  return `${proto}://${req.headers.host}`;
}
function json(res, status, payload) { res.statusCode = status; res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.setHeader('Cache-Control', 'no-store'); res.end(JSON.stringify(payload)); }
async function readJson(req) { if (req.body && typeof req.body === 'object') return req.body; if (typeof req.body === 'string') return req.body ? JSON.parse(req.body) : {}; const chunks = []; for await (const chunk of req) chunks.push(chunk); if (!chunks.length) return {}; const raw = Buffer.concat(chunks).toString('utf8'); return raw ? JSON.parse(raw) : {}; }
function normalizePhone(value) { return String(value || '').replace(/[^0-9+]/g, '').trim(); }
function normalizePlate(value) { return String(value || '').toUpperCase().replace(/[^A-Z0-9]/g, '').trim(); }
function sanitizeText(value, max = 120) { return String(value || '').trim().slice(0, max); }
function requireEnv(names) { const missing = names.filter((name) => !process.env[name]); if (missing.length) { const error = new Error(`Faltan variables de entorno: ${missing.join(', ')}`); error.statusCode = 500; error.missing = missing; throw error; } }
function argentinaDateString(date = new Date()) { const parts = new Intl.DateTimeFormat('en-US', { timeZone: EVENT_TIME_ZONE, year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(date).reduce((acc, part) => ({ ...acc, [part.type]: part.value }), {}); return `${parts.year}-${parts.month}-${parts.day}`; }
function supabaseConfig() { const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) { const error = new Error('Falta configurar SUPABASE_URL y SUPABASE_SERVICE_ROLE_KEY.'); error.statusCode = 500; error.missing = ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'].filter((name) => !process.env[name]); throw error; } return { url: url.replace(/\/$/, ''), key }; }
async function supabaseRequest(path, options = {}) { const { url, key } = supabaseConfig(); const response = await fetch(`${url}${path}`, { ...options, headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); const text = await response.text(); const data = text ? JSON.parse(text) : null; if (!response.ok) { const error = new Error(data?.message || data?.error || `Supabase error ${response.status}`); error.statusCode = response.status; error.data = data; throw error; } return data; }
async function insertOrder(payload) { const data = await supabaseRequest('/rest/v1/event_orders', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(payload) }); return Array.isArray(data) ? data[0] : data; }
async function getOrderById(id) { if (!id) return null; const data = await supabaseRequest(`/rest/v1/event_orders?id=eq.${encodeURIComponent(id)}&select=*`, { method: 'GET' }); return Array.isArray(data) ? data[0] || null : null; }
async function getOrderByTicketCode(code) { if (!code) return null; const data = await supabaseRequest(`/rest/v1/event_orders?ticket_code=eq.${encodeURIComponent(code)}&select=*`, { method: 'GET' }); return Array.isArray(data) ? data[0] || null : null; }
async function getAcceptedCheckinsForDate(ticketCode, eventDate = argentinaDateString()) { if (!ticketCode) return []; const data = await supabaseRequest(`/rest/v1/event_access_logs?ticket_code=eq.${encodeURIComponent(ticketCode)}&action=eq.checkin&select=created_at,result,details&order=created_at.desc&limit=200`, { method: 'GET' }); const acceptedResults = new Set(['ok', 'reentry_ok', 'daily_checkin_ok']); return (Array.isArray(data) ? data : []).filter((log) => acceptedResults.has(log.result) && argentinaDateString(new Date(log.created_at)) === eventDate); }
async function updateOrder(id, payload) { const data = await supabaseRequest(`/rest/v1/event_orders?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', headers: { Prefer: 'return=representation' }, body: JSON.stringify({ ...payload, updated_at: new Date().toISOString() }) }); return Array.isArray(data) ? data[0] : data; }
async function insertAccessLog(payload) { try { await supabaseRequest('/rest/v1/event_access_logs', { method: 'POST', headers: { Prefer: 'return=minimal' }, body: JSON.stringify(payload) }); } catch (error) { console.error('No se pudo registrar access log', error.message); } }
function generateTicketCode(product) { return `SC-RF27-${product?.prefix || 'SC'}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`; }
function publicOrder(order) { if (!order) return null; return { id: order.id, status: order.status, product_code: order.product_code, product_name: order.product_name, amount: Number(order.amount), currency: order.currency || 'ARS', buyer_name: order.buyer_name, buyer_phone: order.buyer_phone, vehicle_type: order.vehicle_type, vehicle_plate: order.vehicle_plate, ticket_code: order.ticket_code, ticket_url: order.ticket_url, checked_in_at: order.checked_in_at, box_delivered_at: order.box_delivered_at, whatsapp_sent_at: order.whatsapp_sent_at, created_at: order.created_at, updated_at: order.updated_at }; }
function validatorView(order) { const product = PRODUCTS[order.product_code] || {}; return { id: order.id, status: order.status, product_code: order.product_code, product_name: order.product_name, amount: Number(order.amount), buyer_name: order.buyer_name, buyer_phone: order.buyer_phone, vehicle_type: order.vehicle_type, vehicle_plate: order.vehicle_plate, ticket_code: order.ticket_code, checked_in_at: order.checked_in_at, checked_in_count: order.checked_in_count || 0, box_delivered_at: order.box_delivered_at, includes_box: Boolean(product.includesBox), created_at: order.created_at }; }
function assertValidatorPin(req, body = {}) { const expected = process.env.VALIDATOR_PIN; if (!expected) { const error = new Error('Falta configurar VALIDATOR_PIN para habilitar validación en puerta.'); error.statusCode = 500; throw error; } const provided = body.pin || req.headers['x-validator-pin'] || req.query?.pin; if (String(provided || '') !== String(expected)) { const error = new Error('PIN de validación incorrecto.'); error.statusCode = 401; throw error; } }
function mapPaymentStatus(mpStatus) { if (mpStatus === 'approved') return 'paid'; if (['cancelled', 'refunded', 'charged_back'].includes(mpStatus)) return 'cancelled'; if (mpStatus === 'rejected') return 'rejected'; return 'pending'; }
async function fetchMercadoPagoPayment(paymentId) { requireEnv(['MERCADOPAGO_ACCESS_TOKEN']); const response = await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(paymentId)}`, { headers: { Authorization: `Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}` } }); const data = await response.json(); if (!response.ok) { const error = new Error(data?.message || `Mercado Pago error ${response.status}`); error.statusCode = response.status; error.data = data; throw error; } return data; }
async function createMercadoPagoPreference({ order, product, baseUrl }) { requireEnv(['MERCADOPAGO_ACCESS_TOKEN']); const response = await fetch('https://api.mercadopago.com/checkout/preferences', { method: 'POST', headers: { Authorization: `Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ external_reference: order.id, notification_url: `${baseUrl}/api/evento/mp-webhook`, back_urls: { success: `${baseUrl}/evento/confirmacion.html?order_id=${order.id}`, pending: `${baseUrl}/evento/confirmacion.html?order_id=${order.id}`, failure: `${baseUrl}/evento/confirmacion.html?order_id=${order.id}` }, auto_return: 'approved', statement_descriptor: 'STYLO CAMION', items: [{ id: product.code, title: product.name, description: product.description, quantity: 1, unit_price: Number(product.amount), currency_id: 'ARS' }], payer: { name: order.buyer_name, email: order.buyer_email || undefined, phone: { number: order.buyer_phone } }, metadata: { event_slug: EVENT_SLUG, product_code: product.code, vehicle_plate: order.vehicle_plate || null } }) }); const data = await response.json(); if (!response.ok) { const error = new Error(data?.message || `No se pudo crear preferencia de Mercado Pago (${response.status})`); error.statusCode = response.status; error.data = data; throw error; } return data; }
async function sendWhatsAppTicket(order) { const token = process.env.WHATSAPP_ACCESS_TOKEN; const phoneNumberId = process.env.WHATSAPP_PHONE_NUMBER_ID; if (!token || !phoneNumberId || !order.buyer_phone || !order.ticket_code) return { sent: false, reason: 'whatsapp_not_configured' }; const to = normalizePhone(order.buyer_phone).replace(/^\+/, ''); const body = [`Tu ingreso a ${EVENT_NAME} está confirmado.`, '', `Producto: ${order.product_name}`, order.vehicle_plate ? `Patente: ${order.vehicle_plate}` : null, `Código: ${order.ticket_code}`, '', `Validación: ${order.ticket_url}`, '', 'Presentá este código o QR en el ingreso al Autódromo de Rafaela. Válido para los 4 días, con 1 ingreso por día.'].filter(Boolean).join('\n'); const response = await fetch(`https://graph.facebook.com/v20.0/${phoneNumberId}/messages`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ messaging_product: 'whatsapp', to, type: 'text', text: { preview_url: true, body } }) }); const data = await response.json(); if (!response.ok) { console.error('WhatsApp error', data); return { sent: false, reason: data?.error?.message || 'whatsapp_error' }; } return { sent: true, data }; }
async function approveOrderFromPayment(payment, req) { const orderId = payment.external_reference || payment.metadata?.order_id; if (!orderId) throw new Error('El pago no tiene external_reference para unirlo con una orden interna.'); const order = await getOrderById(orderId); if (!order) throw new Error(`No existe la orden interna ${orderId}.`); const product = PRODUCTS[order.product_code]; const paidAmount = Number(payment.transaction_amount || 0); const expectedAmount = Number(order.amount || product?.amount || 0); const paymentStatus = mapPaymentStatus(payment.status); const baseUpdate = { status: paymentStatus, mp_payment_id: String(payment.id), mp_status: payment.status, mp_raw: payment }; if (payment.status !== 'approved') return updateOrder(order.id, baseUpdate); if (Math.round(paidAmount * 100) !== Math.round(expectedAmount * 100)) { await insertAccessLog({ order_id: order.id, ticket_code: order.ticket_code, action: 'payment_amount_mismatch', result: 'blocked', details: { paidAmount, expectedAmount, payment_id: payment.id } }); const error = new Error('El monto aprobado no coincide con la orden interna.'); error.statusCode = 409; throw error; } const baseUrl = getBaseUrl(req); const ticketCode = order.ticket_code || generateTicketCode(product); const ticketUrl = `${baseUrl}/evento/ticket.html?code=${encodeURIComponent(ticketCode)}`; let updated = await updateOrder(order.id, { ...baseUpdate, status: 'paid', ticket_code: ticketCode, ticket_url: ticketUrl, paid_at: order.paid_at || new Date().toISOString() }); if (!updated.whatsapp_sent_at) { const whatsapp = await sendWhatsAppTicket(updated); if (whatsapp.sent) updated = await updateOrder(order.id, { whatsapp_sent_at: new Date().toISOString() }); } await insertAccessLog({ order_id: updated.id, ticket_code: updated.ticket_code, action: 'payment_approved', result: 'ok', details: { payment_id: payment.id, status: payment.status } }); return updated; }
function methodNotAllowed(res, methods = ['POST']) { res.setHeader('Allow', methods.join(', ')); return json(res, 405, { ok: false, error: 'Método no permitido.' }); }
function handleError(res, error) { console.error(error); return json(res, error.statusCode || 500, { ok: false, error: error.message || 'Error interno.', missing: error.missing }); }

module.exports = { EVENT_SLUG, EVENT_NAME, EVENT_TIME_ZONE, PRODUCTS, approveOrderFromPayment, argentinaDateString, assertValidatorPin, createMercadoPagoPreference, fetchMercadoPagoPayment, getAcceptedCheckinsForDate, getBaseUrl, getOrderById, getOrderByTicketCode, handleError, insertAccessLog, insertOrder, json, methodNotAllowed, normalizePhone, normalizePlate, publicOrder, readJson, sanitizeText, updateOrder, validatorView };
